services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Respons11
      POSTGRES_DB: sahc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
  api:
    build: ./backend
    container_name: sahc_api
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Respons11
      POSTGRES_DB: sahc
      POSTGRES_PORT: 5432
      MAILING_USER: ascodeinfrastructure766@gmail.com
      MAILING_PASSWORD: insm bbto pbqk mhix
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000/
    container_name: sahc_frontend
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - api

  adminer:
    image: adminer
    container_name: sahc_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
